# Notebook 1.1 - Regressão (Equação Normal) - Previsão da Potência Gerada em Painéis Solares Utilizando Regressão Linear

Os dados consistem em:
*   Potência gerada pelo painel (variável alvo);
*   Irradiação solar (principal variável preditora), temperatura ambiente e velocidade do vento (variáveis complementares) - *features*.

In [ ]:
# here we load data by GitHub

import pandas as pd

github_excel_url = 'https://github.com/tiagoz-gif/aula_regressao/raw/refs/heads/main/solar_IFES_ex1.xlsx'


# the data is loaded into a pandas DataFrame
# the parameter header=0 indicates that the first row of the Excel file contains the column names
df = pd.read_excel(github_excel_url, header=0)

# Shoow the first 5 rows of the DataFrame
df.head()

   T. Ambiente (°C)  Veloc. Vento (m/s)  Irradiação (W/m²)   P (W)
0            29.750                0.70              351.6   57.24
1            29.813                0.96              671.9  203.53
2            29.875                0.68              789.1  282.46
3            30.000                0.29              781.2  280.89
4            29.938                1.05              781.2  280.46

In [4]:
df.describe()

       T. Ambiente (°C)  Veloc. Vento (m/s)  Irradiação (W/m²)         P (W)
count      28719.000000        28719.000000       28719.000000  28719.000000
mean          24.461903           20.705186         194.767276     68.159932
std            4.728830            2.296486         305.674734    106.301822
min           16.688000            0.000000           0.000000      0.000000
25%           20.938000           20.980000           0.000000      0.000000
50%           22.750000           20.980000           0.000000      0.000000
75%           27.250000           20.980000         328.100000    120.735000
max           39.688000           20.980000        1273.400000    414.810000

In [6]:
# the shape is a tuple that represents the dimensions of the DataFrame, columns and rows. 
# The first element of the tuple is the number of rows, and the second element is the number of columns.
df.shape

(28719, 4)

# 2 - Regressão Linear


Neste exemplo, queremos prever a potência gerada pelo painel solar a partir da irradiação solar.

Modelo desejado:

$$\hat{P} = \theta_0 + \theta_1 I$$

em que:

- $\hat{P}$ é a potência prevista, em watts;
- $I$ é a irradiação solar, em W/m²;
- $\theta_0$ é o intercepto da reta;
- $\theta_1$ é o coeficiente angular da reta.

In [ ]:
# We do select the irradiance variable as the independent variable (X) and the power variable as the dependent variable (y).

X = df[['Irradiação (W/m²)']]

# We can use other options such as df.iloc[:, 2] to select the third column such as varible X
# X = df.loc[:, 'Irradicação(W/m²)']  # This will select the column by name

# Now we select the dependent variable (y) as the power variable

Y = df[['P (W)']]

#Outras alternativas
#Y = df.iloc[:,3]  # Seleciona a quarta coluna (índice 3) como variável Y
#Y = df.loc[:, 'P (W)']   Seleciona a coluna de Potência (W) pelo nome